import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} text-white bg-primary`}>
				<Navbar />
				<div className="grid grid-cols-1 sm:grid-cols-[300px,1fr]">
					<Sidebar />
					{children}
				</div>
			</body>
		</html>
	);
}
